on:
  push:
    tags:
    - '[0-9]+.[0-9]+.[0-9]+'
    - '[0-9]+.[0-9]+.[0-9]+-rc'
    - '[0-9]+.[0-9]+.[0-9]+(-rc)?'
    - '[0-9]+.[0-9]+.[0-9]+-rc[0-9]+'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: viamrobotics/build-action@v1
      with:
        version: ${{ github.ref_name }}
        ref: ${{ github.sha }}
        key-id: ${{ secrets.viam_key_id }}
        key-value: ${{ secrets.viam_key_value }}