name: Run lint & unit tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: "Run unit tests"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: stable
    - name: Install dependencies
      run: go mod download

    - name: Run lint
      run: make lint

    - name: Run unit tests
      run: make test